In [20]:
#Importing The Libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [21]:
#Importing The Dataset
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[ : , 3:-1].values #stores the independant values of dataset into x
y = dataset.iloc[ : , -1].values #stores the dependant values into y

In [22]:
#Encoding The categorical Data
#Label Encoding The 'Gender' Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])


In [23]:
#One Hot Encoding The 'Geography' Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder #convert our categories into numbers 

ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(), [1])] , remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [24]:
#Splitting The dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size= 0.2 , random_state= 1)

In [25]:
#Feature Scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Building The ANN

In [26]:
#Initializing The ANN
ann = tf.keras.models.Sequential() #Initialises our artificial neural network as sequence of layers


In [27]:
#Adding The input Layer and The first hidden layer

ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu')) #first hidden layer with 6 neurons and rectifier activation function
#Dense class is used because it connects every neuron 
#Adding The 2nd hidden layer
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu')) #first hidden layer with 6 neurons and rectifier activation function

#Adding The Output Layer
ann.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid')) #first hidden layer with 6 neurons and rectifier activation function


Training The ANN

In [28]:
#Compiling The ANN
ann.compile(optimizer = 'adam', loss='binary_crossentropy' , metrics= ['accuracy'])

In [29]:
#Training The ANN on training set
ann.fit(x_train, y_train, batch_size= 32 , epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7943
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4363 - accuracy: 0.7972
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4316 - accuracy: 0.7972
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4287 - accuracy: 0.8043
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.8161
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.8183
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4215 - accuracy: 0.8224
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4194 - accura

In [30]:
#Making The predictions and evaluating The model
#Predicting The result of a single observation
print(ann.predict(sc.transform([[1,0 ,0 ,600,1,40,3,60000,2,1,1,50000]])))

1/1 [==============================] - 0s 144ms/step
[[0.04787806]]


In [31]:
#Predicting The Test set result
y_pred = ann.predict(x_test)
y_pred = (y_pred> 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [32]:
#Making The OCnfusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test,y_pred)
print(matrix)
accuracy_score(y_test, y_pred)

[[1523   62]
 [ 228  187]]


0.855